services:
  mc-server:
    build: .
    container_name: mc-server
    restart: unless-stopped
    ports:
      - "8888:25565"
    volumes:
      - world:/minecraft/world
    environment:
      EULA: ${EULA:-false}
      MINECRAFT_PORT: 25565
      MAX_PLAYERS: 10
      MOTD: "A Minecraft Server"
      DIFFICULTY_LEVEL: easy
      MAX_MEMORY: 2048M
volumes:
  world: