services:
  mc-server:
    build: .
    container_name: mc-server
    restart: unless-stopped
    ports:
      - "8888:25565"
    volumes:
      - world:/minecraft/world
    environment:
      EULA: "TRUE"
      MINECRAFT_PORT: 25565
volumes:
  world: